.*-elastic\d\d:
  - role::elasticsearch::server
.*-mc\d\d:
  - role::memcached
.*-tin:
  - role::deployment::server
.*-sca\d\d:
  - role::sca
.*-ocg\d\d:
  - role::ocg
.*-rdb\d\d?:
  - role::db::redis
.*:
  - role::puppet::self
